const ADMIN_PIN = '421685';
const STORAGE_KEY = 'leave-desk-data-v1';
const palette = ['#1d6863', '#f4f4f2', '#d85b5b', '#6e86ad', '#d19b39', '#8b8d93'];
const employeeColorChoices = [
  { name: '綠', value: '#1d6863' },
  { name: '白', value: '#f4f4f2' },
  { name: '紅', value: '#d85b5b' },
  { name: '藍', value: '#6e86ad' },
  { name: '黃', value: '#d19b39' },
  { name: '灰', value: '#8b8d93' }
];
const seed = { departments: [], employees: [{id: 'e1', name: '林怡君', department: '未分組', color: '#1d6863'}, {id: 'e2', name: '陳柏安', department: '未分組', color: '#6e86ad'}, {id: 'e3', name: '張雅雯', department: '未分組', color: '#d19b39'}, {id: 'e4', name: '王志明', department: '未分組', color: '#6e86ad'}], leaveTypes: [{id: 't1', name: '特休', color: '#1d6863'}, {id: 't2', name: '病假', color: '#d85b5b'}, {id: 't3', name: '事假', color: '#d19b39'}, {id: 't4', name: '補休', color: '#6e86ad'}], leaves: [], logs: [] };
let data = loadData();
let selectedEmployeeColor = employeeColorChoices[0].value;
const $ = selector => document.querySelector(selector);
const adminUnlocked = () => !!($('#adminArea') && !$('#adminArea').classList.contains('locked'));
function requireAdminAction(){ if(!adminUnlocked()){ showToast('請先解鎖管理設定'); return false; } return true; }
function deleteLogsByDate(dateValue, confirmed = false){ if(!dateValue){ showToast('請選擇日期'); return; } if(!confirmed){ openModal('確認刪除指定日異動？', `${dateValue} 的異動紀錄將全部刪除。`, '確認刪除', () => deleteLogsByDate(dateValue, true)); return; } const before = data.logs.length; data.logs = data.logs.filter(item => item.time.slice(0,10) !== dateValue); const removed = before - data.logs.length; if(!removed){ showToast('此日期沒有異動紀錄'); return; } save(); renderLogs(); showToast(`已刪除 ${removed} 筆異動紀錄`); }
function deleteLogsByMonth(monthValue, confirmed = false){ if(!monthValue){ showToast('請選擇月份'); return; } if(!confirmed){ openModal('確認刪除指定月異動？', `${monthValue} 的異動紀錄將全部刪除。`, '確認刪除', () => deleteLogsByMonth(monthValue, true)); return; } const prefix = monthValue.slice(0,7); const before = data.logs.length; data.logs = data.logs.filter(item => item.time.slice(0,7) !== prefix); const removed = before - data.logs.length; if(!removed){ showToast('此月份沒有異動紀錄'); return; } save(); renderLogs(); showToast(`已刪除 ${removed} 筆異動紀錄`); }
function deleteHistoryByDate(dateValue, confirmed = false){ if(!dateValue){ showToast('請選擇日期'); return; } if(!confirmed){ openModal('確認刪除指定日歷史假單？', `${dateValue} 的歷史假單將全部刪除。`, '確認刪除', () => deleteHistoryByDate(dateValue, true)); return; } const before = data.leaves.filter(item => !item.deleted && item.endDate < iso(today) && (item.startDate === dateValue || item.endDate === dateValue || (item.startDate <= dateValue && item.endDate >= dateValue))).length; const nextLeaves = data.leaves.filter(item => !( !item.deleted && item.endDate < iso(today) && (item.startDate === dateValue || item.endDate === dateValue || (item.startDate <= dateValue && item.endDate >= dateValue)))); if(!before){ showToast('此日期沒有歷史假單'); return; } data.leaves = nextLeaves; save(); renderAll(); showToast(`已刪除 ${before} 筆歷史假單`); }
function deleteHistoryByMonth(monthValue, confirmed = false){ if(!monthValue){ showToast('請選擇月份'); return; } if(!confirmed){ openModal('確認刪除指定月歷史假單？', `${monthValue} 的歷史假單將全部刪除。`, '確認刪除', () => deleteHistoryByMonth(monthValue, true)); return; } const prefix = monthValue.slice(0,7); const before = data.leaves.filter(item => !item.deleted && item.endDate < iso(today) && (item.startDate.slice(0,7) === prefix || item.endDate.slice(0,7) === prefix || (item.startDate <= `${prefix}-31` && item.endDate >= `${prefix}-01`))).length; const nextLeaves = data.leaves.filter(item => !( !item.deleted && item.endDate < iso(today) && (item.startDate.slice(0,7) === prefix || item.endDate.slice(0,7) === prefix || (item.startDate <= `${prefix}-31` && item.endDate >= `${prefix}-01`)))); if(!before){ showToast('此月份沒有歷史假單'); return; } data.leaves = nextLeaves; save(); renderAll(); showToast(`已刪除 ${before} 筆歷史假單`); }
const today = new Date();
const iso = date => date.toISOString().slice(0, 10);
const fmtDate = value => value ? new Intl.DateTimeFormat('zh-TW', {month:'numeric', day:'numeric'}).format(new Date(`${value}T00:00:00`)) : '';
const fmtLongDate = value => value ? new Intl.DateTimeFormat('zh-TW', {year:'numeric', month:'long', day:'numeric'}).format(new Date(`${value}T00:00:00`)) : '';
const weekdays = ['日','一','二','三','四','五','六'];
function loadData(){ try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || structuredClone(seed); } catch { return structuredClone(seed); } }
function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); renderAll(); }
function uid(prefix){ return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function employeeName(id){ return data.employees.find(item => item.id === id)?.name || '已刪除人員'; }
function typeName(id){ return data.leaveTypes.find(item => item.id === id)?.name || id || '未分類'; }
function log(action, detail){ data.logs.unshift({id: uid('log'), action, detail, time: new Date().toISOString()}); }
function showToast(message){ const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
function setToday(){ const date = iso(today); $('#todayLabel').textContent = fmtLongDate(date); $('#todayWeekday').textContent = `星期${weekdays[today.getDay()]}`; $('#headingDate').textContent = fmtLongDate(date); $('#headingWeekday').textContent = `星期${weekdays[today.getDay()]}`; $('#startDate').value ||= date; $('#endDate').value ||= date; }
function setView(view){ document.querySelectorAll('.view').forEach(item => item.classList.toggle('active', item.id === `view-${view}`)); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); window.scrollTo({top:0, behavior:'smooth'}); }
function renderSelects(){ const employees=data.employees.filter(item=>item.active!==false); $('#employeeSelect').innerHTML=employees.map(item=>`<option value="${item.id}">${item.name}</option>`).join(''); $('#employeePicker').innerHTML=employees.map(item=>`<button type="button" class="employee-chip" data-employee="${item.id}" style="--chip-color:${item.color}"><span class="color-chip"></span>${item.name}</button>`).join(''); $('#leaveTypeSelect').innerHTML=`<option value="">選擇常用假別</option>${data.leaveTypes.filter(item=>item.active!==false).map(item=>`<option value="${item.id}">${item.name}</option>`).join('')}`; }
function activeLeaves(){ return data.leaves.filter(item => !item.deleted); }
function isCurrentLeave(item){ return typeof item.endDate === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(item.endDate) && item.endDate >= iso(today); }
function isHistoryLeave(item){ return typeof item.endDate === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(item.endDate) && item.endDate < iso(today); }
function renderStats(){ const current=activeLeaves(); const todayLeaves=current.filter(item=>item.startDate<=iso(today)&&item.endDate>=iso(today)); const weekEnd=new Date(today); weekEnd.setDate(today.getDate()+6); const weekCount=current.filter(item=>item.startDate<=iso(weekEnd)&&item.endDate>=iso(today)).length; $('#todayCount').textContent=todayLeaves.length; $('#weekCount').textContent=weekCount; }
function leaveMarkup(item, history = false){ const employee = data.employees.find(person => person.id === item.employeeId); const color = employee?.color || '#1d6863'; const time = item.startDate === item.endDate ? `${item.startTime} - ${item.endTime}` : `${fmtDate(item.startDate)} - ${fmtDate(item.endDate)}`; const actions = history ? `<button class="card-button" title="刪除這一天" data-delete-history-day="${item.id}" data-leave-day="${item.startDate}">×</button>` : `<button class="card-button" title="修改這一天" data-edit-day="${item.id}" data-leave-day="${item.startDate}">✎</button><button class="card-button" title="刪除這一天" data-delete-day="${item.id}" data-leave-day="${item.startDate}">×</button>`; return `<article class="leave-card" style="border-left-color:${color}"><div class="leave-card-main"><strong>${employeeName(item.employeeId)}</strong><div class="leave-card-meta"><span>${typeName(item.leaveType || item.customType)}</span><span>·</span><span>${time}</span></div>${item.note ? `<small>${item.note}</small>` : ''}</div><div class="leave-card-actions">${actions}</div></article>`; }
function expandLeavesByDay(list){ return list.flatMap(item => { const days=[]; const cursor=new Date(`${item.startDate}T00:00:00`); const end=new Date(`${item.endDate}T00:00:00`); while(cursor<=end){ const date=`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}-${String(cursor.getDate()).padStart(2,'0')}`; days.push({...item,startDate:date,endDate:date}); cursor.setDate(cursor.getDate()+1); } return days; }); }
function groupLeaves(list, history = false){ const groups = {}; list.sort((a,b) => a.startDate.localeCompare(b.startDate)).forEach(item => { (groups[item.startDate] ||= []).push(item); }); return Object.entries(groups).map(([date, items]) => `<section class="date-group"><div class="date-heading"><strong>${fmtDate(date)}</strong><span>星期${weekdays[new Date(`${date}T00:00:00`).getDay()]} · ${items.length} 筆</span></div><div class="date-list">${items.map(item => leaveMarkup(item, history)).join('')}</div></section>`).join('') || '<div class="empty-state">目前沒有符合條件的假單。<br />團隊的時間，留白也是一種答案。</div>'; }
function renderUpcoming(){ const list=activeLeaves().filter(item=>item.startDate<=iso(today)&&item.endDate>=iso(today)); $('#upcomingList').innerHTML=list.length?list.map(item=>`<div class="upcoming-item" style="border-left-color:${data.employees.find(person=>person.id===item.employeeId)?.color||'#1d6863'}"><div><strong>${employeeName(item.employeeId)}</strong><small>${typeName(item.leaveType||item.customType)} · ${item.startTime}-${item.endTime}</small></div><strong>今日</strong></div>`).join(''):'<div class="empty-state">今天沒有請假紀錄。</div>'; }
function renderCurrent(){ const query = ($('#currentSearch')?.value || '').toLowerCase(); const list = activeLeaves().filter(isCurrentLeave).filter(item => `${employeeName(item.employeeId)} ${typeName(item.leaveType || item.customType)}`.toLowerCase().includes(query)); const currentDays = expandLeavesByDay(list).filter(item => item.startDate >= iso(today)); $('#currentList').innerHTML = groupLeaves(currentDays); }
function renderHistory(){ const query = ($('#historySearch')?.value || '').toLowerCase(); const list = activeLeaves().filter(isHistoryLeave).filter(item => `${employeeName(item.employeeId)} ${typeName(item.leaveType || item.customType)}`.toLowerCase().includes(query)); $('#historyList').innerHTML = groupLeaves(expandLeavesByDay(list), true); }
function renderLogs(){ $('#logsList').innerHTML = data.logs.length ? data.logs.map(item => `<div class="log-row"><span class="log-time">${new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(item.time))}</span><span class="log-action">${item.action}</span><span class="log-detail">${item.detail}</span><button class="card-button" title="刪除此筆異動" data-delete-log="${item.id}">×</button></div>`).join('') : '<div class="empty-state">尚無異動紀錄。</div>'; }
function syncAdminDeleteControls(){ const unlocked = !$('#adminArea')?.classList.contains('locked'); const controls = document.querySelectorAll('.admin-delete-controls'); controls.forEach(control => control.classList.toggle('hidden', !unlocked)); }
function renderAll(){ renderSelects(); renderStats(); renderUpcoming(); renderCurrent(); renderHistory(); renderLogs(); syncAdminDeleteControls(); }
function resetForm(){ $('#leaveForm').reset(); $('#editingId').value=''; $('#formTitle').textContent='新增請假紀錄'; $('#submitLabel').textContent='建立假單'; $('#startTime').value='08:00'; $('#endTime').value='17:00'; $('#startDate').value=iso(today); $('#endDate').value=iso(today); document.querySelectorAll('.employee-chip').forEach(item=>item.classList.remove('selected')); }
function dateRange(startDate,endDate){ const dates=[]; const cursor=new Date(`${startDate}T00:00:00`); const end=new Date(`${endDate}T00:00:00`); while(cursor<=end){ dates.push(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}-${String(cursor.getDate()).padStart(2,'0')}`); cursor.setDate(cursor.getDate()+1); } return dates; }
function commitLeave({selected,leaveType,customType,startDate,endDate,startTime,endTime,editingId}){ if(editingId){const item=data.leaves.find(leave=>leave.id===editingId);Object.assign(item,{employeeId:selected[0],leaveType,customType,startDate,endDate,startTime,endTime});log('修改假單',`${employeeName(selected[0])} · ${customType||typeName(leaveType)} · ${fmtDate(startDate)}`);showToast('假單已更新');}else{const dates=dateRange(startDate,endDate);selected.forEach(employeeId=>{dates.forEach(date=>data.leaves.push({id:uid('leave'),employeeId,leaveType,customType,startDate:date,endDate:date,startTime,endTime,deleted:false}));log('新增假單',`${employeeName(employeeId)} · ${customType||typeName(leaveType)} · ${fmtDate(startDate)}${startDate!==endDate?`-${fmtDate(endDate)}`:''}`);});showToast(selected.length>1?`已建立 ${selected.length*dates.length} 筆每日假單`:`已建立 ${dates.length} 筆每日假單`);}save();resetForm();}
function submitLeave(event){event.preventDefault();const selected=[...$('#employeeSelect').selectedOptions].map(option=>option.value);const leaveType=$('#leaveTypeSelect').value;const customType=$('#customType').value.trim();const startDate=$('#startDate').value,endDate=$('#endDate').value,startTime=$('#startTime').value,endTime=$('#endTime').value;if(!selected.length||(!leaveType&&!customType)){showToast('請選擇人員，並選擇或輸入假別');return;}if(`${startDate}${startTime}`>`${endDate}${endTime}`){showToast('結束時間不能早於開始時間');return;}const editingId=$('#editingId').value;const overlaps=selected.flatMap(employeeId=>activeLeaves().filter(item=>item.employeeId===employeeId&&item.id!==editingId&&item.startDate<=endDate&&item.endDate>=startDate).map(item=>`${employeeName(employeeId)}（${fmtDate(item.startDate)}-${fmtDate(item.endDate)}）`));$('#overlapWarning').style.display=overlaps.length?'block':'none';if(overlaps.length){$('#overlapWarning').textContent=`提醒：${overlaps.join('、')} 已有重疊假單，請確認後再送出。`;openModal('發現重疊請假',`${overlaps.join('<br />')}<br /><small>確認後仍會建立這筆假單。</small>`,'確認送出',()=>commitLeave({selected,leaveType,customType,startDate,endDate,startTime,endTime,editingId}));return;}commitLeave({selected,leaveType,customType,startDate,endDate,startTime,endTime,editingId});}
function shiftDate(value, offset){ const date=new Date(`${value}T00:00:00`); date.setDate(date.getDate()+offset); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
function splitLeaveDay(id, day){ const item=data.leaves.find(leave=>leave.id===id); if(!item||day<item.startDate||day>item.endDate||item.startDate===item.endDate)return item; const pieces=[]; if(item.startDate<day)pieces.push({...item,id:uid('leave'),endDate:shiftDate(day,-1)}); const target={...item,id:uid('leave'),startDate:day,endDate:day}; pieces.push(target); if(day<item.endDate)pieces.push({...item,id:uid('leave'),startDate:shiftDate(day,1)}); data.leaves=data.leaves.flatMap(leave=>leave.id===id?pieces:[leave]); return target; }
function deleteLeave(id, day){ const item=data.leaves.find(leave=>leave.id===id); if(!item)return; const targetDate=day||item.startDate; openModal('刪除這一天的假單？', `${employeeName(item.employeeId)}｜${fmtDate(targetDate)}｜${typeName(item.leaveType || item.customType)}<br /><small>其他日期的假單不會受到影響。</small>`, '確認刪除', () => { const target=splitLeaveDay(id,targetDate); if(!target)return; target.deleted=true; target.deletedAt=new Date().toISOString(); log('刪除假單', `${employeeName(target.employeeId)} · ${fmtDate(target.startDate)}`); save(); showToast('當日假單已刪除'); }); }
function deleteHistoryItem(id, day){ if(!requireAdminAction())return; const item=data.leaves.find(leave=>leave.id===id); if(!item)return; const targetDate=day||item.startDate; openModal('刪除這一天的歷史假單？', `${employeeName(item.employeeId)}｜${fmtDate(targetDate)}｜${typeName(item.leaveType || item.customType)}<br /><small>其他日期的歷史假單不會受到影響。</small>`, '確認刪除', () => { const target=splitLeaveDay(id,targetDate); if(!target)return; data.leaves=data.leaves.filter(leave=>leave.id!==target.id); log('刪除歷史假單', `${employeeName(target.employeeId)} · ${fmtDate(target.startDate)}`); save(); showToast('當日歷史假單已刪除'); }); }
function deleteLog(id){ if(!requireAdminAction())return; const item=data.logs.find(logItem=>logItem.id===id); if(!item)return; openModal('刪除這筆異動紀錄？', `${item.action}｜${item.detail}`, '確認刪除', () => { data.logs = data.logs.filter(logItem => logItem.id !== id); save(); showToast('異動紀錄已刪除'); }); }
function editLeave(id, day){ const item=day?splitLeaveDay(id,day):data.leaves.find(leave=>leave.id===id); if(!item)return; setView('overview'); $('#editingId').value=item.id; $('#formTitle').textContent='修改請假紀錄'; $('#submitLabel').textContent='儲存修改'; [...$('#employeeSelect').options].forEach(option=>option.selected=option.value===item.employeeId); document.querySelectorAll('.employee-chip').forEach(chip=>chip.classList.toggle('selected',chip.dataset.employee===item.employeeId)); $('#leaveTypeSelect').value=item.leaveType||''; $('#customType').value=item.customType||''; $('#startDate').value=item.startDate; $('#endDate').value=item.endDate; $('#startTime').value=item.startTime; $('#endTime').value=item.endTime; window.scrollTo({top:0,behavior:'smooth'}); }
function openModal(title, content, confirmLabel, onConfirm){ $('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>${title}</h2><p>${content}</p><div class="modal-actions"><button class="button button-ghost" data-close-modal>取消</button><button class="button button-primary" id="modalConfirm">${confirmLabel}</button></div></div></div>`; $('#modalConfirm').onclick=()=>{onConfirm();$('#modalRoot').innerHTML='';}; $('[data-close-modal]').onclick=()=>$('#modalRoot').innerHTML=''; }
function unlockAdmin(){ openModal('管理設定', '請輸入管理密碼以開啟人員與假別管理。<input id="pinInput" type="password" inputmode="numeric" maxlength="6" placeholder="6 位數密碼" />', '解鎖', ()=>{ if($('#pinInput').value===ADMIN_PIN){ $('#adminArea').classList.remove('locked'); renderAdmin(); $('#unlockAdmin').textContent='已解鎖'; syncAdminDeleteControls(); $('#modalRoot').innerHTML=''; showToast('管理設定已解鎖'); } else showToast('密碼不正確'); }); setTimeout(()=>$('#pinInput')?.focus(),50); }
function renderAdmin(){ $('#adminArea').innerHTML=`<div class="admin-grid"><section class="admin-panel"><div class="panel-heading"><div><span class="section-kicker">TEAM</span><h2>人員名單</h2></div></div><div class="inline-form"><input id="newEmployee" placeholder="新增人員姓名" /><div class="color-picker">${employeeColorChoices.map(choice=>`<button type="button" class="color-swatch ${selectedEmployeeColor===choice.value?'selected':''}" data-employee-color="${choice.value}" style="background:${choice.value}" aria-label="${choice.name}色" title="${choice.name}色"></button>`).join('')}</div><button class="button button-primary" id="addEmployee">新增</button></div><div class="managed-list">${data.employees.filter(person=>person.active!==false).map(person=>`<div class="managed-row"><div class="managed-meta"><span class="color-chip" style="background:${person.color}"></span><div><strong>${person.name}</strong>${person.department && person.department !== '未分組' ? `<small>${person.department}</small>` : ''}</div></div><button class="mini-action" data-remove-person="${person.id}">×</button></div>`).join('')}</div></section><section class="admin-panel"><div class="panel-heading"><div><span class="section-kicker">LEAVE TYPES</span><h2>常用假別</h2></div></div><div class="inline-form"><input id="newType" placeholder="新增假別名稱" /><button class="button button-primary" id="addType">新增</button></div><div class="managed-list">${data.leaveTypes.filter(type=>type.active!==false).map(type=>`<div class="managed-row"><div class="managed-meta"><span class="color-chip" style="background:${type.color}"></span><strong>${type.name}</strong></div><button class="mini-action" data-remove-type="${type.id}">×</button></div>`).join('')}</div></section></div>`; $('#addEmployee').onclick=()=>{const name=$('#newEmployee').value.trim();if(!name)return;data.employees.push({id:uid('employee'),name,department:'未分組',color:selectedEmployeeColor});log('新增人員',`${name}（${employeeColorChoices.find(item=>item.value===selectedEmployeeColor)?.name || '自訂'}色）`);save();renderAdmin();showToast('人員已新增');}; $('#addType').onclick=()=>{const name=$('#newType').value.trim();if(!name)return;data.leaveTypes.push({id:uid('type'),name,color:palette[data.leaveTypes.length%palette.length]});log('新增假別',name);save();renderAdmin();showToast('假別已新增');}; }
function csvExport(list, filename){ const rows=[['人員','假別','開始日期','結束日期','開始時間','結束時間'],...list.map(item=>[employeeName(item.employeeId),typeName(item.leaveType||item.customType),item.startDate,item.endDate,item.startTime,item.endTime])]; const blob=new Blob(['\ufeff'+rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}); const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=filename;link.click();URL.revokeObjectURL(link.href); }
document.addEventListener('click', event=>{ const employeeColorButton = event.target.closest('[data-employee-color]'); if(employeeColorButton){ selectedEmployeeColor = employeeColorButton.dataset.employeeColor; document.querySelectorAll('.color-swatch').forEach(item => item.classList.toggle('selected', item.dataset.employeeColor === selectedEmployeeColor)); return; } const nav=event.target.closest('[data-view]'); if(nav)setView(nav.dataset.view); const link=event.target.closest('[data-view-link]');if(link)setView(link.dataset.viewLink); const editDay=event.target.closest('[data-edit-day]');if(editDay)editLeave(editDay.dataset.editDay,editDay.dataset.leaveDay); const delDay=event.target.closest('[data-delete-day]');if(delDay)deleteLeave(delDay.dataset.deleteDay,delDay.dataset.leaveDay); const historyDelDay=event.target.closest('[data-delete-history-day]');if(historyDelDay)deleteHistoryItem(historyDelDay.dataset.deleteHistoryDay,historyDelDay.dataset.leaveDay); const edit=event.target.closest('[data-edit]');if(edit)editLeave(edit.dataset.edit); const del=event.target.closest('[data-delete]');if(del)deleteLeave(del.dataset.delete); const historyDel=event.target.closest('[data-delete-history]');if(historyDel)deleteHistoryItem(historyDel.dataset.deleteHistory); const logDel=event.target.closest('[data-delete-log]');if(logDel)deleteLog(logDel.dataset.deleteLog); const person=event.target.closest('[data-remove-person]');if(person){data.employees.find(item=>item.id===person.dataset.removePerson).active=false;log('停用人員',employeeName(person.dataset.removePerson));save();renderAdmin();showToast('人員已停用');} const type=event.target.closest('[data-remove-type]');if(type){data.leaveTypes.find(item=>item.id===type.dataset.removeType).active=false;log('停用假別',typeName(type.dataset.removeType));save();renderAdmin();showToast('假別已停用');} });
$('#leaveForm').addEventListener('submit',submitLeave); $('#cancelEdit').onclick=resetForm; $('#currentSearch').oninput=renderCurrent; $('#historySearch').oninput=renderHistory; $('#unlockAdmin').onclick=unlockAdmin; $('#unlockAdminInside').onclick=unlockAdmin; $('#refreshButton').onclick=()=>{data=loadData();renderAll();showToast('資料已重新整理');}; $('#exportCurrent').onclick=()=>csvExport(activeLeaves().filter(item=>item.endDate>=iso(today)),'目前假單.csv'); $('#exportHistory').onclick=()=>csvExport(activeLeaves().filter(item=>item.endDate<iso(today)),'歷史假單.csv'); $('#deleteHistoryByDate').onclick=()=>{ if(!requireAdminAction()) return; deleteHistoryByDate($('#historyDeleteDate').value); }; $('#deleteHistoryByMonth').onclick=()=>{ if(!requireAdminAction()) return; deleteHistoryByMonth($('#historyDeleteMonth').value); }; $('#deleteLogsByDate').onclick=()=>{ if(!requireAdminAction()) return; deleteLogsByDate($('#logDeleteDate').value); }; $('#deleteLogsByMonth').onclick=()=>{ if(!requireAdminAction()) return; deleteLogsByMonth($('#logDeleteMonth').value); }; $('#exportLogs').onclick=()=>{const content=data.logs.map(item=>[item.time,item.action,item.detail].join('\t')).join('\n');const blob=new Blob(['時間\t操作\t內容\n'+content],{type:'text/tab-separated-values;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='異動紀錄.tsv';link.click();}; setToday(); renderAll();